package game;

public enum ClapperRailAsset {
	BACKGROUND("BACKGROUND"),
	ENERGY("ENERGY_ICON"),
	CRAB("CRAB"),
	STICK("STICK"),
	PLATFORM("PLATFORM"),
	TUTORIALIMAGE1("TUTORIALIMAGE1"),
	TUTORIALIMAGE2("TUTORIALIMAGE2"),
	TUTORIALIMAGE3("TUTORIALIMAGE3"),
	TUTORIALIMAGE4("TUTORIALIMAGE4"),
	TUTORIALIMAGE5("TUTORIALIMAGE5"),
	TUTORIALIMAGE6("TUTORIALIMAGE6"),
	TUTORIALIMAGE7("TUTORIALIMAGE7");
	
	

	private String asset_key = null;

	private ClapperRailAsset(String s){
		asset_key=s;
	}
}
