package game;

public enum ClapperRailAsset2 {
	BACKGROUND("BACKGROUND"),
	BACKGROUND2("BACKGROUND2"),
	WATER("WATER"),
	ENERGY("ENERGY_ICON"),
	CRAB("CRAB"),
	STICK("STICK"),
	PLATFORM("PLATFORM"),
	CLAPPERBIRD("CLAPPERBIRD"),
	QUESTIONBLOCK("QUESTIONBLOCK"),
	TUTORIALIMAGE1("TUTORIALIMAGE1"),
	TUTORIALIMAGE2("TUTORIALIMAGE2"),
	TUTORIALIMAGE3("TUTORIALIMAGE3"),
	TUTORIALIMAGE4("TUTORIALIMAGE4"),
	TUTORIALIMAGE5("TUTORIALIMAGE5"),
	TUTORIALIMAGE6("TUTORIALIMAGE6"),
	TUTORIALIMAGE7("TUTORIALIMAGE7"),
	TUTORIALIMAGE8("TUTORIALIMAGE8"),
	TUTORIALIMAGE9("TUTORIALIMAGE9");
	
	

	private String asset_key = null;

	private ClapperRailAsset2(String s){
		asset_key=s;
	}
}
